### ISSUE TITLE
docs: unclear points about resource readiness checks

### ISSUE THREAD

**Issue by ahmetb** [tilt-dev/tilt.build#1003]
Hi dear docs maintainers, I was reading https://docs.tilt.dev/resource_dependencies.html#adding-readiness-checks-for-startup-waiting and two prominent points made me think.

1. How is readiness defined? I think it is alluding to the Kubernetes status conditions described at https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties in other words, does Tilt look for:

	  ```
	  status:
	    conditions:
	    - type: Ready
	      status: "True"
	  ```

     The documentation does not make this clear.

2. Which type of workload objects does the Tilt look for, to check readiness? I see that the Pods are recognized (and presumably builtin workload controllers as well). However, for example:
    * does it know that it should wait for a Kubernetes Job to complete (a type that does not have a `Ready` condition) or,
    * how does a CRD that provides `Ready` condition (such as a knative Service CRD) work? do I need to opt-in explicitly as described in https://docs.tilt.dev/custom_resource.html#does-it-create-pods

I appreciate the answers. (But more importantly than answering to me, I wanted to point out that the docs do not make these points clear and I assume others wonder about similar things as they read the doc set.)

**Comment by lizzthabet** [comment]
@ahmetb, those are great questions! i appreciate you opening an issue to ask for better documentation.

tilt looks at pods and jobs to determine readiness for kubernetes resources. a pod is considered ready when all of its containers are ready, (which may take into account readiness probes if they're defined on a container). a job is considered ready when it has completed. 

if a k8s workload object, including a CRD, doesn't create pods, there isn't a way for tilt to know when it's ready. that's why there's a `pod_readiness='ignore'` option, which tells tilt that it shouldn't be waiting for pods to show up to determine a resource's readiness. 

there are a couple [CRD examples](https://docs.tilt.dev/custom_resource.html#custom-resource-examples) linked in our docs, if that's helpful, or you can take a look at the [knative extension](https://github.com/tilt-dev/tilt-extensions/tree/master/knative) for more info about what that looks like in practice.

i'll follow up with a docs pr, too.

**Comment by ahmetb** [comment]
> if a k8s workload object, including a CRD, doesn't create pods, there isn't a way for tilt to know when it's ready.

I think this definition is inherently problematic. For example, Knative Service CRD creates Pods but deletes them later if they don't receive any requests. The readiness definition for many CRDs (incl. Knative) is converging towards the kstatus convention (the snippet/link I added in my original comment).

Would it be noteworthy to consider looking at status.conditions[*].type~Ready.status=="True" to determine readiness of other resources? I suspect this convention is only going to get more widespread, and can be a good indicator, if present.

**Comment by lizzthabet** [comment]
let's move our discussion over to [#3301](https://github.com/tilt-dev/tilt/issues/3301), so other tilt folks can chime in and this issue for docs can be closed. upvotes and comments on existing issues are great, since it helps us gauge interest/need.

i'll tag you and include your comments there.

**Comment by Venryx** [comment]
For others looking for how to "wait for CRDs to be ready", the key part from the examples is here: https://github.com/tilt-dev/tilt-example-frameworks/blob/5d8554023431587916400917f2b716edebe99ad5/prometheus/Tiltfile#L39

However, I found the `kubectl wait` command wasn't finding the CRD I wanted it to wait for, for some reason.

Because of that, I switched to using the [tilt wait](https://docs.tilt.dev/cli/tilt_wait.html) command instead:
```
k8s_resource(new_name="my-crd-definition",
	objects=[my_crd_name],
	pod_readiness="ignore")

# wait until the CRD is ready
local_resource("my-crd-definition-ready",
	cmd="tilt wait --for=condition=Ready uiresource/my-crd-definition",
	resource_deps=["my-crd-definition"])

k8s_resource('the-resource-afterward',
	resource_deps=["my-crd-definition-ready"])
```
